apiVersion: v1
kind: Pod
metadata:
  name: simple-image-test
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "ls -la /mnt/image-volume && cat /mnt/image-volume/etc/alpine-release && sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: image-volume
      mountPath: /mnt/image-volume
      readOnly: true
  volumes:
  - name: image-volume
    image:
      reference: docker.io/library/alpine:latest